server.port=9090
spring.application.name=ismp-backend
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_odisha_sap_portal
spring.datasource.username=postgres
spring.datasource.password=ambuj

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

